package com.optimove.optimove_sdk.optitrack;

public enum EventSentResult {
    SUCCESS,
    UNKNOWN_EVENT_NAME_ERROR,
    INVALID_PARAMETER_NAME_ERROR,
    VALUE_TOO_LARGE_ERROR,
    MISSING_MANDATORY_PARAMETER_ERROR,
    INCORRECT_VALUE_TYPE_ERROR
}
